import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { Log } from '@/components/Log'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Log>{children}</Log>
      </body>
    </html>
  )
}
